version: '3.9'

services:
 
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


  data_service:
    container_name: data_service
    build: data
    links:
      - rabbitmq
      - mongodb1
    depends_on:
      - rabbitmq
      

  create_user:
    container_name: login
    build: login/
    ports: 
      - "5000:5000"
    links:
      - rabbitmq

  mongodb1:
    container_name: mongodb1
    image: mongo
    volumes:
      - "./db:/data/db"
    ports:
      - 27017:27017

networks:
   my-mongo-cluster:
